extra_css:
- https://assets.readthedocs.org/static/css/badge_only.css
- https://assets.readthedocs.org/static/css/readthedocs-doc-embed.css
extra_javascript:
- readthedocs-data.js
- https://assets.readthedocs.org/static/core/js/readthedocs-doc-embed.js
- https://assets.readthedocs.org/static/javascript/readthedocs-analytics.js
google_analytics: null
site_name: KendonBCaster
site_author: dictation-toolbox
site_url: https://kendonbcaster.readthedocs.io
docs_dir: castervoice/doc
repo_url: https://github.com/kendonb/caster

nav:
    - 'Home': '../../ReadMe.md'
