extra_css:
- https://assets.readthedocs.org/static/css/badge_only.css
- https://assets.readthedocs.org/static/css/readthedocs-doc-embed.css
extra_javascript:
- readthedocs-data.js
- https://assets.readthedocs.org/static/core/js/readthedocs-doc-embed.js
- https://assets.readthedocs.org/static/javascript/readthedocs-analytics.js
google_analytics: null
site_name: KendonBCaster
site_author: dictation-toolbox
site_url: https://kendonbcaster.readthedocs.io
docs_dir: castervoice/doc
repo_url: https://github.com/kendonb/caster

nav:
    - 'Home': ../../ReadMe.md
    - 'Home': Contributing.md
    - 'Home': Installation.md
    - 'Home': readthedocs/Aenea.md
    - 'Home': readthedocs/Alias.md
    - 'Home': readthedocs/Application_Commands_Quick_Reference.md
    - 'Home': readthedocs/Auto_CCR_and_Cmd-Mode.md
    - 'Home': readthedocs/CCR.md
    - 'Home': readthedocs/CCR_languages_Quick_Reference.md
    - 'Home': readthedocs/ContextStack.md
    - 'Home': readthedocs/Mouse.md
    - 'Home': readthedocs/NodeRule.md
    - 'Home': readthedocs/Record_Macros.md
    - 'Home': readthedocs/Setup.md
    - 'Home': readthedocs/Sikuli.md
    - 'Home': readthedocs/Taxonomy_of_a_Rule.md
    - 'Home': readthedocs/Voice_Index.md
    - 'Home': readthedocs/Windows_Speech_Recognition.md
    - 'Home': readthedocs/Examples/How_to_Speak_Code.md
    - 'Home': readthedocs/Examples/Rule_Construction.md
    - 'Home': readthedocs/Examples/Speaking/Examples.md
    - 'Home': readthedocs/Examples/rules/Caster_Rules.md
    - 'Home': readthedocs/Examples/rules/Dragonfly_Rules.md
    - 'Home': readthedocs/Examples/rules/Old_Sample_File.md
    - 'Home': readthedocs/meta/Undocumented_Features.md 